# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=marketplace_user
      - POSTGRES_PASSWORD=marketplace123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace_user -d marketplace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate_schemas --shared &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-secret-key
      - DB_NAME=marketplace_db
      - DB_USER=marketplace_user
      - DB_PASSWORD=marketplace123
      - DB_HOST=db
      - DB_PORT=5432
      - IS_DOCKER=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: